# -*- coding: utf-8 -*-
"""estatistica descritiva com dados do titanic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nu1fMdCgXKRx3DYZDWCbQqUyBQrC5jsV
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from google.colab import files
uploaded = files.upload()

titanic = pd.read_csv("train.csv") 
titanic.head() #ler

titanic.info() #estruturação e tipo de dados do csv

titanic.head(4)

titanic.shape

titanic.describe()

titanic.isnull().sum() #quantos dados faltantes temos no banco de dados

titanic.fillna(titanic["Age"].dropna().median(),inplace = True) #ajuste dos dados de idade que faltam com média

titanic.isnull().sum() #sem dado faltante

#Plotando sobreviventes
titanic.plot(kind="scatter", x="Fare", y= "Survived", color = "r", linewidth=1)#ACIMA SOBREVIVEU, ABAIXO FALECEU

#Sobreviventes em relação a classe do navio
sns.barplot(x="Pclass", y="Survived",data=titanic)
#A primeira classe tem maior percentual de sobrevivente

#Sobreviventes em relação ao sexo
sns.barplot(x="Sex", y="Survived",data=titanic)